### ISSUE TITLE
Meta Issue for Gitcoin Bounty

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#172]
# **Assigment:** Add to the ConsenSys Best Practices repository

## Description

Our documentation should be updated to remain current. We are looking to work with a single contributor who can: 

1. Write in a similar [style](https://consensys.github.io/smart-contract-best-practices/about/contributing/#style-guidelines) as the existing content
2. Has a strong understanding of solidity and the EVM
3. Can ask well formulated questions, and perform their own research in order to flesh out the very brief descriptions in issues listed below
4. Has reviewed the existing content, understands the layout, and can make good judgements about where to add new content.

The following issues describe the work to be done.

- [x] #169 
- [x] #170 
- [x] #83 (the most recent comments need to be addressed)
- [x] #55 
- [x] #133

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $28,746.93 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by Destiner** [comment]
Hi @maurelian. Interested in the project.
As far as I understand, this task requires researching through the provided issues and then adding 5 entries to either Recommendations or Known Attacks (from the first glance, most of them belong to the former) with short code samples.
Sounds good?

**Comment by maurelian** [comment]
That's sounds accurate to me. I like your work on the SWC registry, so let's get going. :) 

You can find me on the Mythril discord if you have questions.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 4 weeks, 1 day from now.
Please review their action plans below:


**1) [Destiner](https://gitcoin.co/profile/Destiner) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?mutate_worker_action=approve&worker=Destiner) | [reject worker](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?mutate_worker_action=reject&worker=Destiner))_.**

I'll start with rereading docs to get a better sense of a writing style and content, then I'll prepare drafts, discuss them, and add code samples.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341).

**Comment by Destiner** [comment]
Submitted #176, #177, #178.

**Comment by maurelian** [comment]
Merged those!

**Comment by Destiner** [comment]
Added #180 and #181.

**Comment by gitcoinbot** [comment]
@Destiner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=1) | [3 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=3) | [5 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=5) | [10 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=10) | [100 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=100)

**Comment by gitcoinbot** [comment]
@Destiner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=1) | [3 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=3) | [5 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=5) | [10 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=10) | [100 days](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341?snooze=100)

**Comment by ceresstation** [comment]
@Destiner Sorry about that, just turned off the bot for a few days!

**Comment by maurelian** [comment]
Great work @Destiner. Just merged that last one!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 500.0 DAI (500.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@Destiner](https://gitcoin.co/profile/Destiner)



@ceresstation please take a look at the submitted work:
* (Link Not Provided) by @Destiner

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $47,422.68 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by ceresstation** [comment]
Awesome job again @Destiner, paying out the bounty now!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @Destiner.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $48,211.12 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @Destiner.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ConsenSys/smart-contract-best-practices/172/1341)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $48,211.12 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
